---
resources:
- name: github-repository
  type: git
  source:
    uri: https://github.com/allomov/incident-registration-app.git
    branch: master
- name: cf-staging
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: staging
    skip_cert_check: true
- name: cf-production
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production
    skip_cert_check: false


# ------------


jobs:
- name: unit-tests
  plan:
  - get: github-repository
    trigger: true
  - task: unit-tests
    file: github-repository/pipeline/tasks/unit-tests.yml
- name: functional-tests
  plan:
  - get: github-repository
    trigger: true
  - task: functional-tests
    file: github-repository/pipeline/tasks/functional-tests.yml
- name: deploy-to-stagging-cf
  plan:
  - get: github-repository
    passed:
      - unit-tests
      - functional-tests
    trigger: true
  - put: cf-staging
    params:
      path: github-repository
      manifest: github-repository/pipeline/manifests/staging-manifest.yml
- name: acceptance-tests
  plan:
  - get: github-repository
    passed: ["deploy-to-stagging-cf"]
    trigger: true
  - get: cf-staging
    passed: ["deploy-to-stagging-cf"]
    trigger: true
  - task: acceptance-tests
    file: github-repository/pipeline/tasks/acceptance-tests.yml
- name: blue-green-deployment-to-production-cf
  plan:
  - get: github-repository
    passed: ["acceptance-tests"]
    trigger: true
  - task: blue-green-deployment-to-production-cf
    file: github-repository/pipeline/tasks/functional-tests.yml
  - put: cf-production
    params:
      path: github-repository
      manifest: github-repository/pipeline/manifests/production-manifest.yml



