---
resources:
- name: github-repository
  type: git
  source:
    uri: https://github.com/allomov/incident-registration-app.git
    branch: master

- name: slack-notification
  type: slack-notification
  source:
    url: {{slack-notification-url}}

jobs:
- name: unit-tests
  plan:
  - get: github-repository
    trigger: true
  - put: slack-notification
    params:
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
      text: "Обнаружена новая версия приложения incident-registration, запускаю тесты в pipeline: http://192.168.100.4:8080/pipelines/continuous-deployment"
  - task: unit-tests
    file: github-repository/pipeline/tasks/unit-tests.yml        

- name: functional-tests
  plan:
  - get: github-repository
    trigger: true
  - task: functional-tests
    file: github-repository/pipeline/tasks/functional-tests.yml

- name: web-ui-tests
  plan:
  - get: github-repository
    trigger: true
  - task: web-ui-tests
    file: github-repository/pipeline/tasks/functional-tests.yml

- name: deploy-to-staging-cf
  plan:
  - get: github-repository
    passed:
      - unit-tests
      - functional-tests
      - web-ui-tests
    trigger: true
  - put: slack-notification
    params:
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_emoji: ":robot_face:"
      text: "Все тесты успешно пройдены, начинаю деплоить на staging: http://staging-incident-registration.pcf.altoros.com"

  - task: deploy-to-stagging-cf
    file: github-repository/pipeline/tasks/deploy-to-staging.yml
    config:
      params:
        cf_api: {{cf-api}}
        cf_username: {{cf-username}}
        cf_password: {{cf-password}}
        cf_org: {{cf-org}}
        cf_space: "staging"
        app_name: "staging-incident-registration"
        app_folder: "github-repository"

  - put: slack-notification
    params:
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_emoji: ":robot_face:"
      text: "Приложение успешно задеплоено на staging: http://staging-incident-registration.pcf.altoros.com"

- name: acceptance-tests
  plan:
  - get: github-repository
    passed: ["deploy-to-staging-cf"]
    trigger: true
  - task: acceptance-tests
    file: github-repository/pipeline/tasks/acceptance-tests.yml
    on_failure:
      do:
      - put: slack-notification
        params:
          channel: {{slack-channel}}
          username: {{slack-username}}
          icon_emoji: ":robot_face:"
          text: "Acceptance tests не прошли :( Проверьте этот лог http://192.168.100.4:8080/pipelines/continuous-deployment/jobs/acceptance-tests или посмотрите логи приложения с помощью команды `cf logs staging-incident-registration-green-version`"
    on_success:
      do:
      - put: slack-notification
        params:
          channel: {{slack-channel}}
          username: {{slack-username}}
          icon_emoji: ":robot_face:"
          text: "Acceptance tests прошли! Начинаю деплоить на production http://192.168.100.4:8080/pipelines/continuous-deployment/jobs/blue-green-deployment-to-production-cf"

- name: blue-green-deployment-to-production-cf
  plan:
  - get: github-repository
    passed: ["acceptance-tests"]
    trigger: true
  - task: blue-green-deployment-to-production-cf
    file: github-repository/pipeline/tasks/deploy-to-production.yml
    config:
      params:
        cf_api: {{cf-api}}
        cf_username: {{cf-username}}
        cf_password: {{cf-password}}
        cf_org: {{cf-org}}
        cf_space: "production"
        app_name: "incident-registration"
        app_folder: "github-repository"
  - put: slack-notification
    params:
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_emoji: ":robot_face:"
      text: "Приложение успешно обновлено: http://incident-registration.pcf.altoros.com"
