---
applications:
- name: staging-incident-registration
  memory: 1G
  instances: 1
  command: rake assetpack:precompile && rackup -p $PORT
  buildpack: https://github.com/cloudfoundry/ruby-buildpack
